### ISSUE TITLE
Add a client-side file size check

### ISSUE THREAD

**Issue by Lemmmy** [Upflask/Upflask#2]

**Comment by Lemmmy** [comment]
you should stop hosting on a pi, get a droplet or something

**Comment by thebitstick** [comment]
It has a file limit of 40MB in the terms.  
I _could_ raise it, but all files are on a USB drive on the Pi.  
Either I get a droplet, or increase the storage.

**Comment by Lemmmy** [comment]
aight im gonna test it on my droplet anyway

still, make the reverse proxy return an error when the file is too large for the www.upflask.cf server, otherwise its a bit confusing

**Comment by Lemmmy** [comment]
just checked you return a 413 from the code but the 600mb file doesnt even reach the server so something is interfering in between the two

**Comment by thebitstick** [comment]
Cloudflare.
I have a 100MB limit

**Comment by Lemmmy** [comment]
welp there it is

i'll pr a clientside size check or something

**Comment by thebitstick** [comment]
There is a client-side check
If it's larger than 40MB, it gives a 413 page with all the languages.

**Comment by Lemmmy** [comment]
nope it just sits there with the loading animation forever, and the upload button keeps flashing

**Comment by Lemmmy** [comment]
http://ichi.lemmmy.pw/effects_lonely_herb.mp4

**Comment by thebitstick** [comment]
OH I read it "client-side" as "server-side" somehow holy hell
Yeah I should add a client-side check

**Comment by Lemmmy** [comment]
btw check #3

**Comment by thebitstick** [comment]
I did and merged it

**Comment by Lemmmy** [comment]
sick fam

**Comment by thebitstick** [comment]
I forgot I already added client-side file size check

**Comment by Lemmmy** [comment]
yay
